In [1]:
import tensorflow as tf

# Defining constants

In [46]:
a = tf.constant(12)
b = tf.constant(3)

c = a + b
d = a * b

print(a)
print(b)
print(c)
print(d)

Tensor("Const_24:0", shape=(), dtype=int32)
Tensor("Const_25:0", shape=(), dtype=int32)
Tensor("add_13:0", shape=(), dtype=int32)
Tensor("mul_9:0", shape=(), dtype=int32)


# TF sessions
Previously the constants were only defined, nothing was evaluated. In order to do that you need a TF session

In [19]:
sess = tf.Session()

In [20]:
sess.run(c)

15

In [21]:
sess.run(d)

36

In [22]:
sess.close()

# Operations with vectors

In [24]:
V1 = tf.constant([1,2,3])
V2 = tf.constant([4,5,6])
V3 = V1 + V2
V4 = V1 * V2
print(V3)
print(V4)

Tensor("add_8:0", shape=(3,), dtype=int32)
Tensor("mul_5:0", shape=(3,), dtype=int32)


In [25]:
sess = tf.Session()

In [26]:
sess.run(V3)

array([5, 7, 9], dtype=int32)

In [27]:
sess.run(V4)

array([ 4, 10, 18], dtype=int32)

In [28]:
sess.close()

# A simplified session
You can open an interactive session and then use the .eval() method to compute the value of each node

In [47]:
sess = tf.InteractiveSession()

In [33]:
V4.eval()

array([ 4, 10, 18], dtype=int32)

# Operations with matrixes

In [39]:
M1 = tf.constant([[1,2,3], [2,1,3], [3,1,2]])
M2 = tf.constant([[4,2,2], [3,2,4], [2,3,4]])

In [40]:
M3 = M1 + M2
M3.eval()

array([[5, 4, 5],
       [5, 3, 7],
       [5, 4, 6]], dtype=int32)

In [41]:
M4 = M1 * M2 # this is not a matrix multiplication, but a 1 to 1 multiplication of elements
M4.eval()

array([[ 4,  4,  6],
       [ 6,  2, 12],
       [ 6,  3,  8]], dtype=int32)

In [43]:
M5 = tf.matmul(M1, M2) # this is a matrix multiplication
M5.eval()

array([[16, 15, 22],
       [17, 15, 20],
       [19, 14, 18]], dtype=int32)

In [44]:
sess.close()